site_name: çŸ¥è¯†ç¬”è®°
site_description: studyRepoå­¦ä¹ ç¬”è®°
# site_author: Xingding Luo
site_author: ç½—å…´å®š
# site_url: https://luoxding.github.io/notes/
# Copyright
copyright: Copyright &copy; 2024 | Xingding Luo

#repo_name: 'notes'
#repo_url: 'https://github.com/luoxding/notes'

# ================================
theme:
  name: material
  features:
    - navigation.instant # å³æ—¶åŠ è½½
    - navigation.path # path å†…æµ‹ç‰ˆæ‰èƒ½ç”¨
    - navigation.sections # å¯¼èˆªæ æ˜¾ç¤ºç« èŠ‚
    - navigation.tabs # nav topç›®å½•æ˜¾ç¤ºåœ¨æ ‡é¢˜æ 
    # - navigation.tabs.sticky # å¯¼èˆªæ ‡ç­¾å°†é”å®šåœ¨é¡µçœ‰ä¸‹é¢ï¼Œå¹¶ä¸”åœ¨å‘ä¸‹æ»šåŠ¨æ—¶å§‹ç»ˆä¿æŒå¯è§ã€‚
    - navigation.top # ä¸€é”®å›é¡¶ top
    - content.code.copy # ä»£ç å¤åˆ¶æŒ‰é’®
    # - toc.integrate #ç›®å½•æ”¾åˆ°å·¦ä¾§å¯¼èˆªæ ï¼Œä»¥åŠ å®½é˜…è¯»é¡µé¢
    # - navigation.indexes # ç« èŠ‚ç´¢å¼•ï¼Œè¿™è¦æ±‚æ¯ä¸ªç›®å½•ä¸‹æœ‰index.mdæ–‡ä»¶
    - content.code.annotate
    - search.highlight # æœç´¢é«˜äº®
    - search.share # æœç´¢å…±äº«
    - search.suggest # æœç´¢å»ºè®®
    - toc.follow # ä¾§è¾¹æ ä¼šè‡ªåŠ¨æ»šåŠ¨
    - navigation.footer # é¡µè„šæ˜¾ç¤ºä¸Šä¸€é¡µ ä¸‹ä¸€é¡µ
  language: 'zh'
  font:
   #text: 'Fira Sans'
    text: 'Noto Sans CJK SC' #Noto Serif CJK SC
    code: 'Fira Mono'
 #palette:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black #white
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode

#  icon:
  logo: assets/figures/chapter_divide_and_conquer.png
  favicon: assets/linux.png

    #logo: fontawesome/brands/suse
   #logo: material/library
  # Don't include MkDocs' JavaScript.
  include_search_page: false
  search_index_only: true

  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - bash
    - latex
    - html

# é¡µé¢å¿«æ·é”®
  shortcuts:
      help: 72    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s



# Customization
extra:
  search:
    language: 'jp'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/luoxding
  #   - icon: fontawesome/solid/paper-plane
  #     link: mailto:anthony_lambert@live.com
  # generator: false #æ¸…é™¤å•†æ ‡

extra_javascript:
  # - '_static/js/extra.js'
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

# extra_css:
#   - '_static/css/extra.css?v=13'

# Extensions begin #############################################################################################################################################
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ğŸ”—
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# Extensions begin #############################################################################################################################################


plugins:
  - blog:
      blog_dir: blog
      blog_toc: true
      authors: true
      post_date_format: medium # æ—¥æœŸæ ¼å¼ 2024 å¹´ 1 æœˆ 31 æ—¥æ˜ŸæœŸä¸€
      authors_file: blog/.authors.yml
      archive_name: Archive
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      archive_url_format: "archive/{date}"
      categories_name: åˆ†ç±»
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"

    # æœç´¢æ’ä»¶
  - search:
      lang: zh
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # å‹ç¼©html
  # - minify:
  #     minify_html: true
  #  - markdownextradata:
  #      data: data
  # è‡ªåŠ¨ç”Ÿæˆå¯¼èˆªæ 
  # - awesome-pages
  # - search:
  #     lang: ja
  #     prebuild_index: true
  # - git-revision-date-localized: #è¿™ä¸¤æ’ä»¶github pagesæ‰ç”¨
  #     type: datetime
  #     enable_creation_date: true
  #     fallback_to_build_date: true
  #     timezone: Asia/Shanghai
  #     locale: zh
  # - git-revision-date:
  #     enabled_if_env: CI
  - literate-nav
#      nav_file: SUMMARY.md

INHERIT: docs/navigation.yml